# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sheetToDb_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SheetToDb_2(object):
    def setupUi(self, SheetToDb_2):
        SheetToDb_2.setObjectName("SheetToDb_2")
        SheetToDb_2.resize(1080, 723)
        self.centralwidget = QtWidgets.QWidget(SheetToDb_2)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 20, 1000, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 1000, 500))
        self.listWidget.setObjectName("listWidget")
        self.btnContinuar = QtWidgets.QPushButton(self.centralwidget)
        self.btnContinuar.setGeometry(QtCore.QRect(850, 590, 200, 63))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnContinuar.setFont(font)
        self.btnContinuar.setCheckable(False)
        self.btnContinuar.setObjectName("btnContinuar")
        self.btnRetroceder = QtWidgets.QPushButton(self.centralwidget)
        self.btnRetroceder.setGeometry(QtCore.QRect(40, 590, 200, 63))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnRetroceder.setFont(font)
        self.btnRetroceder.setCheckable(False)
        self.btnRetroceder.setObjectName("btnRetroceder")
        SheetToDb_2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SheetToDb_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 21))
        self.menubar.setObjectName("menubar")
        SheetToDb_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SheetToDb_2)
        self.statusbar.setObjectName("statusbar")
        SheetToDb_2.setStatusBar(self.statusbar)

        self.retranslateUi(SheetToDb_2)
        QtCore.QMetaObject.connectSlotsByName(SheetToDb_2)

    def retranslateUi(self, SheetToDb_2):
        _translate = QtCore.QCoreApplication.translate
        SheetToDb_2.setWindowTitle(_translate("SheetToDb_2", "Files to import"))
        self.btnContinuar.setText(_translate("SheetToDb_2", "Continuar"))
        self.btnRetroceder.setText(_translate("SheetToDb_2", "Volver"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SheetToDb_2 = QtWidgets.QMainWindow()
    ui = Ui_SheetToDb_2()
    ui.setupUi(SheetToDb_2)
    SheetToDb_2.show()
    #sys.exit(app.exec_())
