# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sheetToDb_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from sheetToDb_2 import Ui_SheetToDb_2

class Ui_MainWindow(object):

    def nextScreen(self):
        #load second screen
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_SheetToDb_2()
        self.ui.setupUi(MainWindow)
        self.MainWindow.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 723)
        self.ArrastrarArchivosWidget = QtWidgets.QWidget(MainWindow)
        self.ArrastrarArchivosWidget.setObjectName("ArrastrarArchivosWidget")
        self.frame = QtWidgets.QFrame(self.ArrastrarArchivosWidget)
        self.frame.setGeometry(QtCore.QRect(40, 20, 1000, 500))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnSeleccionarArchivos = QtWidgets.QPushButton(self.frame)
        self.btnSeleccionarArchivos.setGeometry(QtCore.QRect(290, 310, 427, 63))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnSeleccionarArchivos.setFont(font)
        self.btnSeleccionarArchivos.setObjectName("btnSeleccionarArchivos")
        self.labelArchivosAProcesar = QtWidgets.QLabel(self.frame)
        self.labelArchivosAProcesar.setGeometry(QtCore.QRect(190, 120, 621, 111))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(32)
        self.labelArchivosAProcesar.setFont(font)
        self.labelArchivosAProcesar.setObjectName("labelArchivosAProcesar")
        self.btnContinuar1 = QtWidgets.QPushButton(self.ArrastrarArchivosWidget)
        self.btnContinuar1.setGeometry(QtCore.QRect(860, 560, 200, 63))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnContinuar1.setFont(font)
        self.btnContinuar1.setCheckable(False)
        self.btnContinuar1.setObjectName("btnContinuar1")
        MainWindow.setCentralWidget(self.ArrastrarArchivosWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btnContinuar1.clicked.connect(self.nextScreen)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSeleccionarArchivos.setText(_translate("MainWindow", "Seleccionar archivos"))
        self.labelArchivosAProcesar.setText(_translate("MainWindow", "Arrastra aca tus archivos a procesar"))
        self.btnContinuar1.setText(_translate("MainWindow", "Continuar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
